package week1.exercise01;

import java.util.Scanner;
// --------------------------------------------------------------------------------
// Imagine that you and your band have just recorded a song, and you want to
// permit fans to purchase and download the song over the Internet. Your
// manager receives a commission equal to 12% of the total sales revenue for
// your song, and the Internet site that lists your song receives a 3% commission.
// Write a java program that asks the user for the title of the song, the purchase
// price of the song (in dollars and cents), and the number of copies of the song
// that have been sold. Calculate the total revenue generated by your song, the
// commission received by your manager, and the commission received by the
// Internet site. Use named constants for the commission rates. 
// --------------------------------------------------------------------------------

public class exercise01 {
    public static void main(String[] args) {
        System.out.println("date: 2020-02-18\n");
        Scanner sc = new Scanner(System.in);
        System.out.print("Name of the Song: "); 
        String name = sc.nextLine();
        System.out.print("Price of the Song: ");
        double price = sc.nextDouble();

        System.out.printf("\nName: %s \nPrice: %.2f \nRevenge of the Editor: %.2f \nRevenge of the Manager: %.2f \nRevenge of the Site: %.2f \n\n", name, price, price*0.85, price *0.12, price *0.03);
        sc.close();
    }
}
